import json
import requests
from datetime import datetime


# ============================================================
# OLLAMA CONFIGURATION
# ============================================================

OLLAMA_URL = "http://localhost:11434/api/chat"
OLLAMA_MODEL = "qwen3:4b"


# ============================================================
# ANALYZE TRANSCRIPT
# ============================================================

def analyze_transcript(transcript):

    prompt = f"""
You are an AI meeting assistant analyzing a transcript generated by
automatic speech recognition (ASR).

The transcript may contain transcription errors such as:
- incorrectly recognized words
- missing words
- extra words
- words that sound similar
- incorrect names, technical terms, acronyms, or abbreviations
- French words incorrectly transcribed
- English technical terms incorrectly transcribed
- punctuation or sentence-boundary errors

Your task is to understand the intended meaning of the conversation.

TRANSCRIPTION CORRECTION RULES:

1. Use the surrounding context to identify likely transcription errors.

2. If a word or phrase does not make sense in context, you may infer
   the most likely intended word or phrase.

3. Pay particular attention to:
   - technical terminology
   - company names
   - project names
   - software names
   - product names
   - acronyms
   - people names
   - domain-specific vocabulary

4. Do not blindly trust an unusual or grammatically incorrect
   transcription if the surrounding context strongly suggests another
   interpretation.

5. Only make a correction when the intended meaning is reasonably
   clear from the transcript and its context.

6. If you are uncertain between multiple possible interpretations,
   do NOT invent a specific fact. Preserve the uncertainty.

7. Do not add information that is not supported by the transcript.

8. Do not assume facts from your general knowledge unless they are
   only being used to recognize a likely transcription error.

For example:

Transcript:
"We will use data you key for the analysis."

Context suggests that "Dataiku" is being discussed.

Interpretation:
"We will use Dataiku for the analysis."

This is a transcription correction, not the invention of new information.

MEETING ANALYSIS RULES:

After interpreting and correcting likely transcription errors,
extract the meeting information.

- Do not invent information.
- Only use information explicitly stated or strongly implied by
  correcting an obvious transcription error.
- Keep the summary concise.
- Topics should contain the main subjects discussed.
- Decisions should contain decisions actually made.
- Action items should contain actions that were actually assigned
  or clearly agreed upon.
- Open questions should contain unresolved questions explicitly
  raised during the meeting.
- If there are no decisions, return an empty array.
- If there are no action items, return an empty array.
- If there are no open questions, return an empty array.

Return ONLY valid JSON using exactly this structure:

{{
    "summary": "Short summary of the meeting",
    "topics": [],
    "decisions": [],
    "action_items": [],
    "open_questions": []
}}

Transcript:

{transcript}
"""

    payload = {
        "model": OLLAMA_MODEL,
        "messages": [
            {
                "role": "user",
                "content": prompt
            }
        ],
        "stream": False,

        # Force structured JSON output
        "format": "json",

        # IMPORTANT for Qwen3:
        # We don't need extended reasoning for this task.
        "think": False,

        "options": {
            "temperature": 0.2
        }
    }

    print("→ Calling Ollama API...")
    print(f"→ Model: {OLLAMA_MODEL}")
    print("→ Thinking mode: OFF")
    print("→ Waiting for response...\n")

    try:
        response = requests.post(
            OLLAMA_URL,
            json=payload,
            timeout=300
        )

        response.raise_for_status()

    except requests.exceptions.ConnectionError:
        raise RuntimeError(
            "Could not connect to Ollama.\n"
            "Make sure Ollama is running on "
            "http://localhost:11434"
        )

    except requests.exceptions.Timeout:
        raise RuntimeError(
            "Ollama took too long to respond."
        )

    except requests.exceptions.HTTPError as e:
        raise RuntimeError(
            f"Ollama API error: {e}\n"
            f"Response: {response.text}"
        )

    # ========================================================
    # PARSE OLLAMA RESPONSE
    # ========================================================

    data = response.json()

    content = data["message"]["content"].strip()

    print("✓ Ollama response received.")

    # Safety: remove markdown fences if the model adds them
    if content.startswith("```"):
        content = content.replace("```json", "")
        content = content.replace("```", "")
        content = content.strip()

    try:
        result = json.loads(content)

    except json.JSONDecodeError:
        print("\n❌ Ollama returned invalid JSON:")
        print(content)
        raise

    return result